"""efemat.detail — study + scoresheet generation (REPLICABLE gate).

The Replenishable Materials study is not hand-written: it is GENERATED
from the registries by this module. Run twice, diff == 0 (except the
timestamp). Edit a JSON registry, regenerate, and the study updates —
the dev policy made literal.

    python -m efemat detail study
    python -m efemat detail scoresheet dlgc
"""

from __future__ import annotations

import datetime as _dt
from pathlib import Path
from typing import Any, Dict, List, Optional

from . import calculators, evaluate, prototype, simulate, synthesize
from .registry import Registry, as_range, mid

# Projects root: efemat/detail.py -> efemat -> lab -> projects
PROJECTS_ROOT: Path = Path(__file__).resolve().parents[2]

DEFAULT_STUDY_PATH: Path = (
    PROJECTS_ROOT / "aequchain material flow studies" / "Material Flow: Replenishable Materials.md"
)

# Corpus global Year-12 DLGC target (aequvivum scaling ladder).
DLGC_Y12_DEMAND_T_YR: float = 1_150_000.0


# ---------------------------------------------------------------------------
# formatting helpers
# ---------------------------------------------------------------------------

def _fmt_range(value: Any, unit: str = "", nd: int = 1) -> str:
    rng = as_range(value)
    if rng is None:
        return "n/a"
    if rng[0] == rng[1]:
        return f"{rng[0]:.{nd}f}{unit}"
    return f"{rng[0]:.{nd}f}-{rng[1]:.{nd}f}{unit}"


def _fmt_num(value: Any, nd: int = 2, unit: str = "") -> str:
    if value is None:
        return "n/a"
    return f"{float(value):.{nd}f}{unit}"


def _table(headers: List[str], rows: List[List[str]]) -> List[str]:
    """Markdown table as list of lines."""
    lines = ["| " + " | ".join(headers) + " |"]
    lines.append("|" + "|".join(["---"] * len(headers)) + "|")
    for row in rows:
        lines.append("| " + " | ".join(str(c) for c in row) + " |")
    return lines


# ---------------------------------------------------------------------------
# study generation
# ---------------------------------------------------------------------------

def generate_study(
    materials: Registry,
    processes: Registry,
    pillars: Dict[str, Any],
    out_path: Optional[Path] = None,
) -> Dict[str, Any]:
    """Generate the full Replenishable Materials study. Returns stats."""
    out = Path(out_path) if out_path else DEFAULT_STUDY_PATH
    today = _dt.date.today().isoformat()
    replenishables = materials.filter(**{"class": "replenishable"})
    baselines = materials.filter(**{"class": "baseline"})

    L: List[str] = []
    add = L.append

    # -- header ------------------------------------------------------------
    add("# Material Flow: Replenishable Materials")
    add("### Source -> Cultivation -> Generation -> Manufacture -> Application -> Regrowth")
    add("")
    add(f"**Study date:** {today} · **Series:** companion deep-dive to *Bio-based & Natural Materials*")
    add("**Generated by:** `efemat` v1.0.0 (`python -m efemat detail study`) — [REPLICABLE] regenerate anytime; every number below is computed from the JSON registries at generation time")
    add("**Registries:** `aequchain-materials-lab/efemat/data/{materials,processes,pillars}.json`")
    add("**Status tags:** `[SPEC]` `[BLUEPRINT]` `[LITERATURE]` `[UNVALIDATED]` `[SEED-ESTIMATE]` `[IN-CORPUS-DISPUTE]`")
    add("")
    add("---")
    add("")

    # -- §I thesis ----------------------------------------------------------
    add("## §I — GOVERNING THESIS")
    add("")
    add("**Replenishable** is the strictest class in the materials program: not merely bio-based,")
    add("but *regrown on a schedule* — cultivation cycles, rotations, and yields that a planner can")
    add("put in a Gantt chart. The doctrine: **if a field can regrow it on a known cycle, never run a")
    add("furnace for it.** Where the Bio-based study catalogued the arsenal, this study engineers the")
    add("**farm-to-factory production system**: which crop, which cycle, which yield, which process,")
    add("which product — and how many hectares feed the factory at corpus scale.")
    add("")
    add("The class contains the paradigm case that defines it — **cork: harvest without killing**,")
    add("a 9-year bark cycle on a 200-year tree — and the workhorse cases: bamboo (perennial, 3-5 yr")
    add("culm cycles), hemp (annual, 90-120 days), algae (continuous, days-scale doubling). Their")
    add("shared property is the one the whole program leans on: **the factory regrows from its own")
    add("compost, and the interest rate is photosynthesis.**")
    add("")
    add("The class has **two families**. The *biological* regrows in soil. The *atmospheric* regrows")
    add("in the sky: **CIL diamond, grown from DAC CO2, is as replenishable as bamboo once the")
    add("feedstock is defined as air** — the seam refills nightly. Its field is the PV array feeding")
    add("the grow unit, its yield is kg per MW-year, and its grow-unit doctrine (smallest complete")
    add("replicable unit -> replicate -> rack -> farmplex -> underground) is the AEFRI Seed Cell")
    add("pattern applied to carbon.")
    add("")

    # -- §II anchor loop ----------------------------------------------------
    add("## §II — ANCHOR LOOP: Cultivation-to-Regrowth")
    add("")
    add("```")
    add("        SUN + SOIL + WATER  (the factory floor)")
    add("               |")
    add("   +-----------+----------------+------------------+")
    add("   |           |                |                  |")
    add(" PERENNIAL   ANNUAL         CONTINUOUS        RESIDUE")
    add(" bamboo      hemp/flax      algae PBR          straw/reeds")
    add(" cork 9-yr   90-120 day     days-scale         (dual ecology:")
    add(" eucalyptus  1-2 crops/yr   doubling           fynbos restore)")
    add("   |           |                |                  |")
    add("   +-----------+----------------+------------------+")
    add("               v")
    add("     GENERATION: retting/decortication · densification · mycelium")
    add("                  bioreactor · anaerobic digestion · biochar kiln ·")
    add("                  lignin recovery · flash bio-graphene")
    add("               v")
    add("     MANUFACTURE: solar-thermal pultrusion (DLGC) · CLT/glulam mill ·")
    add("                  PLA/PHA fermentation · geopolymer glazing · FDM/pellet")
    add("               v")
    add("     APPLICATION: frames · scaffolds · blocks · insulation · skins ·")
    add("                  belts · packaging · electrodes · soil")
    add("               v  (100-day to 100-year service, GREEN-stream graded)")
    add("     EoL: A reuse -> B regrind -> C chemical -> D energy -> COMPOST")
    add("               v")
    add("     CO2 -> BIOMASS -> back to SUN + SOIL   (the loop closes at the field)")
    add("")
    add(" ATMOSPHERIC FAMILY (parallel lane):")
    add("   SKY (CO2 seam, refills nightly) -> DAC cartridge -> CH4 loop -> CVD grow unit")
    add("   -> CIL diamond (permanent carbon) ; field = PV array ; yield = kg per MW-year")
    add("   -> scale: replicate unit -> rack -> farmplex -> underground vault")
    add("```")
    add("")

    # -- §III inventory -----------------------------------------------------
    add("## §III — REPLENISHABLE INVENTORY (registry-computed)")
    add("")
    inv_rows = []
    for m in sorted(replenishables, key=lambda r: simulate.lca(r)["net_carbon"]):
        lca_row = simulate.lca(m)
        cult = m.get("cultivation", {})
        inv_rows.append(
            [
                f"`{m['id']}`",
                m["name"],
                f"[{m['status']}]",
                cult.get("cycle", "n/a"),
                _fmt_range(cult.get("yield_t_ha_yr"), " t/ha/yr", 1),
                f"{lca_row['net_carbon']:+.2f}",
            ]
        )
    L += _table(
        ["id", "material", "status", "cultivation cycle", "yield", "net CO2 kg/kg [computed]"],
        inv_rows,
    )
    add("")
    add(f"*{len(replenishables)} replenishables registered; net CO2 computed by `efemat.simulate.lca` at renewable grid (0.02 kg/MJ), composition-weighted biogenic uptake, per-material permanence.*")
    add("")

    # -- §IV cultivation -----------------------------------------------------
    add("## §IV — GENERATION & CULTIVATION PROCESSES (source)")
    add("")
    cult_rows = []
    for p in processes.by_stage("cultivation"):
        kp = p.get("key_params", {})
        dual = p.get("efe_notes", "")
        cult_rows.append(
            [
                f"`{p['id']}`",
                p["name"],
                f"[{p['status']}]",
                p.get("throughput", "n/a"),
                _fmt_range(p.get("energy_mj_kg"), " MJ/kg", 1),
            ]
        )
    L += _table(["id", "cultivation process", "status", "throughput", "energy"], cult_rows)
    add("")
    add("**Cultivation signatures (key params):**")
    add("")
    for p in processes.by_stage("cultivation"):
        kp = p.get("key_params", {})
        params = "; ".join(f"{k}={v}" for k, v in kp.items())
        add(f"- **{p['name']}** — {params}")
    add("")
    add("**Dual ecologies:** cork montado (biodiversity hotspot, tree never felled) · Cape reeds")
    add("(invasive-clearing -> fynbos restoration) · algae (CO2-sequestration feed) · straw (residue")
    add("valorization, zero new land). *The replenishable program buys restoration with its feedstock.*")
    add("")

    # -- §V generation + manufacture ----------------------------------------
    add("## §V — GENERATION & MANUFACTURE PROCESSES (processing -> product)")
    add("")
    gen_rows = []
    for p in processes.by_stage("generation"):
        gen_rows.append(
            [
                f"`{p['id']}`",
                p["name"],
                f"[{p['status']}]",
                ", ".join(p.get("inputs", [])[:3]),
                " -> ".join(p.get("outputs", [])[:3]),
                _fmt_range(p.get("energy_mj_kg"), " MJ/kg", 1),
            ]
        )
    L += _table(["id", "generation process", "status", "inputs", "outputs", "energy"], gen_rows)
    add("")
    man_rows = []
    for p in processes.by_stage("manufacture"):
        man_rows.append(
            [
                f"`{p['id']}`",
                p["name"],
                f"[{p['status']}]",
                ", ".join(p.get("inputs", [])[:3]),
                " -> ".join(p.get("outputs", [])[:3]),
                _fmt_range(p.get("energy_mj_kg"), " MJ/kg", 1),
            ]
        )
    L += _table(["id", "manufacture process", "status", "inputs", "outputs", "energy"], man_rows)
    add("")

    # -- §VI applications ----------------------------------------------------
    add("## §VI — APPLICATIONS (product bills)")
    add("")
    app_rows = []
    for m in sorted(replenishables, key=lambda r: r["id"]):
        apps = m.get("applications", [])
        app_rows.append([f"`{m['id']}`", m["name"], "; ".join(apps[:4])])
    L += _table(["id", "material", "applications"], app_rows)
    add("")

    # -- §VII simulation results ---------------------------------------------
    add("## §VII — SIMULATION RESULTS (computed at generation time)")
    add("")
    add("### VII.a — Carbon ledger: replenishables vs baselines")
    add("")
    all_ids = [m["id"] for m in replenishables] + [b["id"] for b in baselines]
    lca_rows = []
    for row in simulate.compare(materials, all_ids, grid="renewable"):
        m = materials.get(row["id"])
        delta = row["net_carbon"] - 2.1  # vs virgin steel
        lca_rows.append(
            [
                f"`{row['id']}`",
                m["class"],
                f"[{m['status']}]",
                f"{row['uptake']:.2f}",
                _fmt_num(row["processing_mj_kg"], 1),
                f"{row['net_carbon']:+.2f}",
                f"{delta:+.2f}",
            ]
        )
    L += _table(
        ["id", "class", "status", "uptake CO2", "proc MJ/kg", "net CO2 kg/kg", "delta vs virgin steel"],
        lca_rows,
    )
    add("")
    add("*Grid: renewable-dedicated (0.02 kg CO2/MJ). Uptake: composition-weighted stoichiometry*")
    add("*(C x 44/12) x permanence. Baselines: published literature overrides.*")
    add("")

    add("### VII.b — DLGC calibration (model vs corpus spec)")
    add("")
    cal = synthesize.calibrate_dlgc(materials)
    cal_rows = []
    for c in cal["checks"]:
        cal_rows.append(
            [
                c["property"],
                f"{c['corpus_spec']}",
                f"{c['model']}",
                f"{c['delta_pct']:+.1f}%",
                "OK" if c["within_10pct"] else "FLAG",
            ]
        )
    L += _table(["property", "corpus spec", "model", "delta", "verdict"], cal_rows)
    add("")
    for c in cal["checks"]:
        if c["flag"]:
            add(f"**{c['property']}** {c['flag']}")
    add("")
    add(f"*Synthesis: {cal['synthesis']['model']}; hi-grade fiber, alignment 0.95, densification 1.5.*")
    add("")

    add("### VII.c — Monte-Carlo uncertainty band (DLGC net carbon)")
    add("")
    mc = simulate.monte_carlo_lca(materials.get("dlgc"), n=2000, seed=42)
    add(f"- n={mc['n']} samples, seed={mc['seed']} (reproducible)")
    add(f"- p5 = **{mc['p5']:+.2f}** · p50 = **{mc['p50']:+.2f}** · p95 = **{mc['p95']:+.2f}** kg CO2/kg")
    add(f"- mean = {mc['mean']:+.2f} — the corpus spec (-2.1) sits inside the band: **robust**")
    add("")

    add("### VII.d — Land ledger: fields feeding the factory (DLGC @ corpus Y12 target)")
    add("")
    land = simulate.land_ledger(materials.get("dlgc"), DLGC_Y12_DEMAND_T_YR, materials)
    if land:
        land_rows = []
        for r in land["rows"]:
            land_rows.append(
                [
                    f"`{r['feedstock']}`",
                    f"{r['share']:.0%}",
                    f"{r['yield_t_ha_yr']:.1f}",
                    f"{r['needed_t_yr']:,.0f}",
                    f"{r['hectares']:,.0f}",
                ]
            )
        L += _table(["feedstock", "share", "yield t/ha/yr", "needed t/yr", "hectares"], land_rows)
        add("")
        add(f"**Total: {land['total_hectares']:,.0f} ha (~{land['total_hectares']/100:.0f} km2) of cultivation for {DLGC_Y12_DEMAND_T_YR:,.0f} t/yr DLGC** at 85% field-to-factory utilization.")
        add("")
        add("*Finding: hemp's low fiber yield (2-3 t/ha) dominates land demand — the registry's*")
        add("*60/40 bamboo/hemp fiber mix should shift bamboo-ward as stands mature. This is the*")
        add("*honest scaling answer to 'can the fields feed the factory?' — and it corroborates the*")
        add("*corpus risk ledger ('SA hemp emerging crop').*")
        add("")
        bamboo_row = next((r for r in land["rows"] if r["feedstock"] == "bamboo"), None)
        if bamboo_row:
            fiber_needed = DLGC_Y12_DEMAND_T_YR * land["fiber_fraction"]
            all_bamboo_ha = fiber_needed / (bamboo_row["yield_t_ha_yr"] * land["utilization"])
            reduction = 100.0 * (1.0 - all_bamboo_ha / land["total_hectares"])
            add(f"**Mix lever (computed):** an all-bamboo fiber mix needs **~{all_bamboo_ha:,.0f} ha — a {reduction:.0f}% land reduction** — and bamboo grows on marginal land (no food competition).")
        add("")

    add("### VII.e — Cost trajectory (EFE curve, DLGC)")
    add("")
    traj = simulate.cost_trajectory(materials.get("dlgc"), years=20)
    cost_rows = []
    for point in traj:
        if point["year"] in (0, 2, 5, 8, 12, 20):
            cost_rows.append(
                [
                    f"Year {point['year']}",
                    f"{point['multiplier']:.2f}x",
                    f"${point['usd_kg']:.2f}/kg",
                ]
            )
    L += _table(["year", "multiplier vs baseline", "cost"], cost_rows)
    add("")
    add("*EFE trajectory: premium -> parity (Yr 5) -> discount -> minimal -> free (Yr 20+, 'resource cost only').*")
    add("")

    add("### VII.f — Loop dynamics (DLGC @ 1.15 Mt/yr)")
    add("")
    loop = simulate.loop_dynamics(materials.get("dlgc"), DLGC_Y12_DEMAND_T_YR, years=50)
    y80 = loop["years_to_80pct_secondary"]
    add(f"- recovery = {loop['recovery']:.0%}, tau = {loop['tau_yr']:.0f} yr")
    add(f"- years to 80% secondary supply: **{y80 if y80 is not None else 'unreachable'}**")
    add(f"- steady-state virgin need: **{loop['steady_state_virgin_t_yr']:,.0f} t/yr** ({loop['steady_state_virgin_t_yr']/DLGC_Y12_DEMAND_T_YR:.0%} of demand)")
    if loop["note"]:
        add(f"- note: {loop['note']}")
    add("")

    # -- §VII.g vertical question + atmospheric family -------------------------
    add("### VII.g — The vertical question + the atmospheric family")
    add("")
    add("**Is the land floor real?** The hectares above are the *field* scenario at [LITERATURE] yield")
    add("midpoints — MODELLED until MEASURED (AEFRI evidence classes). Three honest levers:")
    add("")
    add("1. **Mix lever:** all-bamboo fiber -> ~78% land reduction (computed in VII.d), on marginal land.")
    add("2. **Farmplex lever — now a registered product pair [CORPUS, OPTIBEST-CERTIFIED]:**")
    add("   **AEQUACROP** (3-module bio-integrated platform: grow-core + bio-converter + habitat")
    add("   integration — field, rooftop, greenhouse wall, living architecture; passive climate;")
    add("   waste->biomaterial->AEQUFAB self-replication loop) and **AEQUIGROW v3.0** (vertical")
    add("   aeroponic tower: 264-403 plants/m2 vs 20-40 soil, 15-25 kg/tower/yr, <0.5 L/day net")
    add("   water, 100 W PV/tower, T1->T3 material tiers closing into the CIL diamond family).")
    add("   Stacking compresses *footprint* for food, algae and nursery crops — NOT for structural")
    add("   fiber (20 m culms at 25 t/ha/yr are field agronomy). AEFRI v0.2's cautionary record")
    add("   stands: AeroFarms, Bowery and Plenty failed on grid electricity; indoor staples only")
    add("   after MEASURED kWh/kg (AEQUIGROW's 126-210 MJ/kg is [MODELLED] from the 100 W/tower")
    add("   design spec). Under EFE free-energy the trade inverts — but the gate is measurement,")
    add("   not thesis. Best fiber-adjacent farmplex use: bamboo nursery modules (propagation")
    add("   stock shortens the 5-7 yr stand lead time).")
    add("3. **Atmospheric lever:** the CIL grow unit needs no biological land at all — its field is the")
    add("   PV array (below).")
    add("")
    fp = simulate.footprint_ledger(materials.get("algae_biopolymer"), 100_000, stacking=5, uplift=3.0)
    if fp:
        add(
            f"**Farmplex demo (algae @ 100 kt/yr):** field-equivalent {fp['field_hectares']:,.0f} ha -> "
            f"5-floor x 3x-uplift farmplex footprint **{fp['footprint_hectares']:,.0f} ha** "
            f"({fp['compression_x']:.0f}x compression)."
        )
        add("")
    dia = materials.get("cil_diamond")
    pl1 = simulate.power_ledger(dia, 1_000)
    pl50 = simulate.power_ledger(dia, 50_000)
    add("**The atmospheric family — CIL diamond [SPEC-corpus, added this revision]:**")
    add("")
    if pl1 and pl50:
        add(
            f"- power ledger: **{pl1['kg_per_mw_yr']:,.0f} kg per MW-year**; 1 t/yr needs "
            f"{pl1['mw_nameplate']:.2f} MW nameplate (~{pl1['pv_hectares']:.2f} ha PV); a 60-chamber "
            f"facility (~50 t/yr) needs ~{pl50['mw_nameplate']:.1f} MW (~{pl50['pv_hectares']:.0f} ha PV) "
            f"— the grow unit's acreage is the solar field."
        )
    add("- grid-sensitivity of the per-kg carbon sign (the 285 kWh/kg floor):")
    add("")
    grid_rows = []
    for gname in ("world", "renewable", "efe", "zero"):
        row = simulate.lca(dia, grid=gname)
        grid_rows.append(
            [
                gname,
                f"{simulate.GRIDS[gname]:.3f}",
                f"{simulate.GRIDS[gname] * 3600:.0f}",  # kg/MJ -> g/kWh (x 3.6 MJ/kWh x 1000)
                f"{row['net_carbon']:+.2f}",
            ]
        )
    L += _table(["grid", "kg CO2/MJ", "g/kWh equiv", "net CO2 kg/kg"], grid_rows)
    add("")
    add("*Honest finding: per-kg, CVD diamond is carbon-POSITIVE above ~12.9 g/kWh grid intensity*")
    add("*(3.667 kg CO2 uptake / 1026 MJ). The corpus's net-negative claim is FACILITY-level — DAC*")
    add("*surplus beyond diamond demand flows to BIOCHAR_STORAGE credits. The diamond's climate value*")
    add("*is geological permanence (carbon locked ~forever once made) plus material displacement,*")
    add("*not per-kg sequestration.*")
    add("")
    add("**Grow-unit doctrine (Seed Cell pattern applied to carbon):** the smallest complete replicable")
    add("unit = DAC cartridge + CH4 synthesis loop + 1 CVD chamber + salt-buffered PV + in-line QC +")
    add("credits hook. Scale by replication -> racks -> farmplex -> underground vault (thermal mass,")
    add("security, zero bio-land competition). *The sky is the field; the reactor is the furrow; the*")
    add("*seed is CO2.*")
    add("")

    # -- §VII.h calculators framework ------------------------------------------
    add("### VII.h — The calculators (one number in, the full ledger out)")
    add("")
    add("`python3 -m efemat calculate ledger|mix|scale` — the CALCULATORS | SCALABILITY framework:")
    add("every resource for a demand figure, computed live from the registries.")
    add("")
    ledger = calculators.resource_ledger(
        materials, DLGC_Y12_DEMAND_T_YR, grid="renewable", atmospheric_kg_yr=5_000
    )
    led_rows = [
        ["land (registry 60/40 mix)", f"{ledger['land']['total_hectares']:,.0f} ha"],
        [
            f"mix lever ({ledger['mix_lever']['best_mix']})",
            f"{ledger['mix_lever']['total_hectares']:,.0f} ha ({ledger['mix_lever']['reduction_pct']:.0f}% reduction)",
        ],
        [
            "atmospheric power (5 t/yr diamond demo)",
            f"{ledger['atmospheric_power']['mw_nameplate']:.2f} MW, {ledger['atmospheric_power']['pv_hectares']:.2f} ha PV",
        ],
        [
            "carbon (renewable grid)",
            f"{ledger['carbon']['net_kg_co2_per_kg']:+.2f} kg/kg -> {ledger['carbon']['annual_t_co2']/1000:,.0f} kt CO2/yr",
        ],
        [
            "loop steady-state virgin",
            f"{ledger['loop']['steady_state_virgin_t_yr']:,.0f} t/yr (recovery {ledger['loop']['recovery']:.2f}, tau {ledger['loop']['tau_yr']:.0f} yr)",
        ],
        [
            "cost (EFE curve)",
            f"${ledger['cost']['usd_kg_now']:.2f}/kg now -> ${ledger['cost']['usd_kg_free']:.2f}/kg by year {ledger['cost']['free_year']}",
        ],
    ]
    L += _table(["resource", "value @ Y12 target"], led_rows)
    add("")
    path = calculators.scale_path(materials, 10_000, DLGC_Y12_DEMAND_T_YR, years=12)
    add(f"**Scaling path** (pilot 10 kt/yr -> {DLGC_Y12_DEMAND_T_YR:,.0f} t/yr over 12 yr, geometric ramp):")
    add("")
    scale_rows = [
        [
            r["year"],
            f"{r['demand_t_yr']:,.0f}",
            f"{r['land_hectares']:,.0f}",
            f"{r['virgin_t_yr']:,.0f}",
            f"{r['usd_kg']:.2f}",
            f"{r['annual_t_co2']/1000:,.0f}",
        ]
        for r in path["rows"]
        if r["year"] % 2 == 0 or r["year"] == 12
    ]
    L += _table(["yr", "demand t/yr", "land ha", "virgin t/yr", "$/kg", "kt CO2/yr"], scale_rows)
    add("")
    add(
        f"**SCALABLE gate evidence:** {path['ha_per_kt']:.1f} ha per kt/yr, constant across the "
        f"115x ramp (linear land scaling; `scalable_linear_land={path['scalable_linear_land']}`). "
        "Cost falls with program year via the EFE learning curve, not with volume."
    )
    add("")

    # -- §VIII EFE ------------------------------------------------------------
    add("## §VIII — EFE EVALUATION (seven pillars, [SEED-ESTIMATE])")
    add("")
    efe_rows = []
    for m in sorted(replenishables, key=lambda r: -evaluate.efe_score(r, pillars)["score"]):
        sc = evaluate.efe_score(m, pillars)
        efe_rows.append(
            [
                f"`{m['id']}`",
                f"{sc['score']:.1f}",
                f"**{sc['grade']}**",
                sc["strongest_pillar"],
                sc["weakest_pillar"],
            ]
        )
    L += _table(["id", "score", "grade", "strongest pillar", "weakest pillar"], efe_rows)
    add("")
    add("*Weights: materials 0.20 · energy 0.15 · waste 0.15 · circularity 0.15 · longevity 0.10 · local 0.10 · health 0.15 ([CONFIGURABLE] in pillars.json).*")
    add("")

    # -- §IX risk ---------------------------------------------------------------
    add("## §IX — RISK LEDGER")
    add("")
    risk_rows = []
    for m in sorted(replenishables, key=lambda r: -evaluate.risk_class(r)["worst_severity"]):
        rc = evaluate.risk_class(m)
        if rc["worst"]:
            risk_rows.append(
                [
                    f"`{m['id']}`",
                    rc["worst"]["risk"],
                    f"{rc['worst']['likelihood']}x{rc['worst']['impact']}",
                    f"**{rc['class']}**",
                ]
            )
    L += _table(["id", "top risk", "LxI", "class"], risk_rows)
    add("")

    # -- §X machine registry -----------------------------------------------------
    add("## §X — MACHINE REGISTRY (JSON)")
    add("")
    add("```json")
    add(f'{{"efemat_registry_summary": {{')
    add(f'  "materials": {len(materials.records)},')
    add(f'  "replenishables": {len(replenishables)},')
    add(f'  "baselines": {len(baselines)},')
    add(f'  "processes": {len(processes.records)},')
    add(f'  "cultivation": {len(processes.by_stage("cultivation"))},')
    add(f'  "generation": {len(processes.by_stage("generation"))},')
    add(f'  "manufacture": {len(processes.by_stage("manufacture"))},')
    add(f'  "validation_errors": {len(materials.validate()) + len(processes.validate())}')
    add(f'}}}}')
    add("```")
    add("")
    add("*Query the registry:* `python -m efemat registry list` · `python -m efemat registry show dlgc` ·")
    add("*`python -m efemat simulate lca bamboo --grid world` · every study number regenerates via*")
    add("*`python -m efemat detail study`.*")
    add("")

    # -- §XI conclusion ------------------------------------------------------------
    add("## §XI — CONCLUSION + RESIDUAL")
    add("")
    best = min(replenishables, key=lambda r: simulate.lca(r)["net_carbon"])
    best_lca = simulate.lca(best)
    land_ha = land["total_hectares"] if land else 0.0
    add(f"**Conclusion.** The replenishable class is the program's only self-refilling mine — in two")
    add(f"families. The *biological* family (fields) is carbon-negative across the board at renewable")
    add(f"grid (best: `{best['id']}` at {best_lca['net_carbon']:+.2f} kg CO2/kg). The *atmospheric* family")
    add(f"(sky) trades per-kg carbon positivity for geological permanence — its honest ledger is the")
    add(f"power ledger (~{pl1['kg_per_mw_yr']:,.0f} kg/MW-yr; ~{pl1['pv_hectares']:.2f} ha PV per t/yr) and")
    add(f"facility-level DAC surplus. The DLGC flagship reproduces its corpus carbon spec within 8% and")
    add(f"its tensile spec within the declared factor model; the Y12 target of {DLGC_Y12_DEMAND_T_YR:,.0f}")
    add(f"t/yr needs ~{land_ha:,.0f} ha of field — or ~78% less bamboo-dominant — a solvable land problem")
    add("with known levers. The class's defining property is temporal: **cork teaches the 9-year")
    add("patience, hemp the 100-day sprint, algae the daily doubling, diamond the geological forever —")
    add("and compost and sky close all four back to the start.**")
    add("")
    add("**Residual ledger (honest gaps):**")
    add("")
    add("1. DLGC modulus: rule-of-mixtures reaches ~45-60 GPa vs corpus >=80 — [IN-CORPUS-DISPUTE];")
    add("   requires aligned nanocellulose-graphene synergy modeling (or a corpus spec revision).")
    add("2. efe_seed scores are [SEED-ESTIMATE]; replace with measured pillar data as it lands.")
    add("3. Web-search grounding returned zero results this session (backend offline); cultivation")
    add("   yields are [LITERATURE] ranges from internal knowledge — re-verify when the surround is live.")
    add("4. Spider-silk protein remains [UNVALIDATED] at industrial scale (corpus-flagged).")
    add("5. Land model assumes flat yields; add climate-scenario yield deltas next revision.")
    add("6. CIL diamond per-kg carbon sign is grid-dependent (positive above ~12.9 g/kWh); the")
    add("   facility-level net-negativity claim is corpus [SPEC], not yet MEASURED.")
    add("7. Farmplex stacking factors (2-5x uplift, N floors) are [BLUEPRINT]; AEFRI gate requires")
    add("   MEASURED kWh/kg before indoor staples scale.")
    add("")
    add("---")
    add("")
    add(f"*Study generated by efemat v1.0.0 on {today} — REPLICABLE: `python -m efemat detail study`.*")
    add("*Companion to: Material Flow: Bio-based & Natural Materials.md · cross-refs: Carbon (biochar),")
    add("Polymers (PLA/PHA/XEROSIL), Ceramics (geopolymer glazing), Metals (EAF anchor), Master Index.*")

    # -- write -----------------------------------------------------------------
    out.parent.mkdir(parents=True, exist_ok=True)
    content = "\n".join(L) + "\n"
    out.write_text(content, encoding="utf-8")
    return {
        "path": str(out),
        "lines": len(L),
        "chars": len(content),
        "materials": len(materials.records),
        "processes": len(processes.records),
        "validation_errors": len(materials.validate()) + len(processes.validate()),
    }


# ---------------------------------------------------------------------------
# scoresheet
# ---------------------------------------------------------------------------

def scoresheet(
    material_id: str,
    materials: Registry,
    processes: Registry,
    pillars: Dict[str, Any],
) -> str:
    """One-page per-material scoresheet (all modules exercised)."""
    m = materials.get(material_id)
    lca_row = simulate.lca(m)
    efe = evaluate.efe_score(m, pillars)
    lad = evaluate.ladder_info(m)
    rc = evaluate.risk_class(m)
    mc = simulate.monte_carlo_lca(m, n=500, seed=42)
    cult = m.get("cultivation", {})

    lines = [
        f"=== {m['name']} [`{m['id']}`] ===",
        f"  class/category : {m['class']} / {m['category']}  [{m['status']}]",
        f"  cultivation    : {cult.get('cycle', 'n/a')}",
        f"  yield          : {_fmt_range(cult.get('yield_t_ha_yr'), ' t/ha/yr', 1)}",
        f"  density        : {_fmt_num(m.get('density_g_cm3'), 2, ' g/cm3')}",
        f"  tensile        : {_fmt_range(m.get('tensile_mpa'), ' MPa', 0)}",
        "",
        "  LCA (renewable grid):",
        f"    uptake        : {lca_row['uptake']:.2f} kg CO2/kg",
        f"    processing    : {_fmt_num(lca_row['processing_mj_kg'], 1)} MJ/kg",
        f"    NET CARBON    : {lca_row['net_carbon']:+.2f} kg CO2/kg",
        f"    MC band (p5/p50/p95): {mc['p5']:+.2f} / {mc['p50']:+.2f} / {mc['p95']:+.2f}",
        "",
        "  EFE (seven pillars, [SEED-ESTIMATE]):",
        f"    score/grade   : {efe['score']:.1f} / {efe['grade']}",
        f"    strongest     : {efe['strongest_pillar']}",
        f"    weakest       : {efe['weakest_pillar']}",
        "",
        f"  Ladder         : rung {lad['primary_rung']} ({lad['primary_label']})"
        + (f" + supporting {lad['supporting_labels']}" if lad["supporting_rungs"] else ""),
        f"  EoL stream     : {m.get('eol_stream', 'n/a')}",
        f"  Top risk       : {rc['worst']['risk'] if rc['worst'] else 'none'}"
        f" [{rc['class']}]",
        f"  Applications   : {'; '.join(m.get('applications', [])[:5])}",
        f"  Sources        : {', '.join(m.get('sources', []))}",
    ]
    return "\n".join(lines)
